version: '3'

services:
  xturn:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        APP_NAME: xturn
        APP_VERSION: 0.1.3
    # image: xirdev/xturn:latest
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    # network_mode: "bridge"
    restart: always
    env_file: .env
    ports:
## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      # - "80"
      # - "80/udp"
## STUN/TURN SSL
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
      # - "443"
      # - "443/udp"
# Relay Ports
      - "49152-65535:49152-65535"
      - "49152-65535:49152-65535/udp"

# networks:
#   default:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.18.0.0/16
