apiVersion: v1
kind: Service
metadata:
  name: xturn-public-udp
spec:
  ports:
  - name: udp-port
    port: 3487
    targetPort: 3487
    protocol: UDP
  - name: dtls-port
    port: 5349
    targetPort: 5349
    protocol: UDP
  selector:
    app: xturn
  type: LoadBalancer